# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Learn Web"
logo: "Learn<span>Web</span>"
email: mahafuzurrahaman1986@gmail.com
description: "This site was created for learning the web development"
baseurl: "/LearnWeb"
url: "https://mahafuzur.github.io"
repository: "mahafuzur/LearnWeb"
collections:
  portfolio:
    output: true

# Build settings
markdown: kramdown
plugins: [jekyll-paginate, jekyll-github-metadata]
paginate: 4
paginate_path: '/blog/page:num/'

# Default for tutorial and snippets

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Monir"
